[[MongoDatastore]]
== MongoDB Datastore

The link:https://www.mongodb.com[MongoDB^] Datastore API is available in three implementations:

* A *synchronous* implementation, which is the reference implementation of the Holon Platform link:{coreapidir}/com/holonplatform/core/datastore/Datastore.html[Datastore^] API: See <<SyncMongoDatastore>>.

* An *asynchronous* implementation, which is the reference implementation of the Holon Platform link:{coreapidir}/com/holonplatform/async/datastore/AsyncDatastore.html[AsyncDatastore^] API: See <<AsyncMongoDatastore>>.

* An *reactive* implementation, which is the reference implementation of the Holon Platform link:{reactorapidir}/com/holonplatform/reactor/datastore/ReactiveDatastore.html[ReactiveDatastore^] API: See <<ReactiveMongoDatastore>>.

[[MongoDBDatastoreConfiguration]]
=== MongoDB Datastore configuration

Regardless of the actual implementation, each MongoDB Datastore provides a set of configuration options, described below.

==== Database name

A MongoDB Datastore is *always bound to a single MongoDB database*, so the the database name configuration is required to build a MongoDB Datastore instance.

Each builder provides a `database(String database)` method to set the *database name* to which the MongoDB Datastore is bound.

Example:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=dbname,indent=0]
----
<1> Obtain a builder to configure and create a new MongoDB Datastore (in this example, a synchronous `MongoDatastore` implementation)
<2> Set the MongoDB client to use
<3> Set the database name to use

==== Common MongoDB Datastore configuration options

A set of common configuration options are available from the MongoDB Datastore builder, regardless of the actual implementation used.

These common configuration options allows to:

* Configure the default *read preference* to use.
* Configure the default *read concern* to use.
* Configure the default *write concern* to use.
* Add a new bson `Codec`.
* Add a new bson `CodecProvider`.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=config1,indent=0]
----
<1> Set the default read preference
<2> Set the default read concern
<3> Set the default write concern
<4> Add a new bson `Codec`
<5> Add a new bson `CodecProvider`

==== `Enum` codec strategy

By default, *enumeration* type document field values are mapped to a Java `Enum` class using a *name based* matching strategy.

An *ordinal based* matching strategy is also available, using the `Enum` ordinal position to map an enumeration type document field value to a Java `Enum` class.

The enumeration codec strategies are listed in the link:{apidir}/com/holonplatform/datastore/mongo/core/document/EnumCodecStrategy.html[EnumCodecStrategy^] enumeration and the strategy to use can be configured using the MongoDB Datastore builder `enumCodecStrategy` method.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=config2,indent=0]
----
<1> Set the enumeration codec strategy to `ORDINAL`

==== Common Datastore API configuration options

Every MongoDB Datastore builder, regardless of the actual implementation, extends the core Datastore builder API, which provides the common Datastore configuration settings listed below.

|===
|Builder method |Arguments |Description

|`dataContextId`
|The _data context id_ `String` value
|Set the _data context id_ to which the Datastore is bound. Can be used, for example, to declare configuration properties for multiple Datastore instances.

|`traceEnabled`
|`true` or `false`
|Whether to enable Datastore operations _tracing_. When enabled, the MongoDB Datastore will log the JSON representation of the documents involved in the performed datastore operations.

|`configuration`
|A `DatastoreConfigProperties` instance
|Set the `DatastoreConfigProperties` type configuration property set instance to use in order to read the Datastore configuration properties. See the link:holon-core.html#DatastoreConfiguration[Datastore configuration^] documentation section for details. This configuration properties can be used as an alternative for the programmatic configuration performed with the previous builder methods. 
|===

Example:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=config3,indent=0]
----
<1> Set a _data context id_ for the Datastore
<2> Activate operations _tracing_ in log

The configuration properties can also be provided through an external configuration property source, using the properties provided by the link:{coreapidir}/com/holonplatform/core/datastore/DatastoreConfigProperties.html[DatastoreConfigProperties^] property set.

For example, supposing to have a properties file named `datastore.properties` like this:

[source, text]
----
holon.datastore.trace=true
----

We can use it as configuration property source to enable the Datastore _tracing_ mode:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=config4,indent=0]
----
<1> Use the `datastore.properties` file as configuration property source

[[DocumentsMapping]]
=== Property model and MongoDB documents mapping

The Holon Platform link:holon-core.html#PropertyBox[PropertyBox^] type, used by the `Datastore` API to collect and handle the data model attributes values using the link:holon-core.html#Property[Property^] model, is mapped into a MongoDB *BSON Document* using the following conventions:

* Each `PropertyBox` instance is mapped into a MongoDB BSON _document_, using the *property set* bound to the `PropertyBox` instance to determine the available document nodes *names*.
* Each *property name* is mapped to a document *node name*. By default only the `Path` type properties are used for mapping, using the *path name* as node name.
* Each *property value* available from the `PropertyBox` instance is mapped into a document *node value*, performing suitable data type convesions if required.

==== Nested documents

Nested MongoDB documents can be represented using either:

*1. Nested property names using a dot notation:*

When _nested path_ names are included in the property set, either using the dot notation or _parent_ path declarations, they will be mapped as *nested document* properties in the MongoDB BSON Document.

For example:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping1,indent=0]
----

The `SUBJECT` property set will be mapped into a _Document_ with:

* A `name` String type node at root level.
* A nested `address` document with the `street` and `city` String type nodes.

*2. Nested `PropertyBox` type properties:*

A `PropertyBox` type property can be used to represent a nested document. The nested document nodes will be the one represented by the *property set* bound to `PropertyBox` type property.

For this purpose, the link:{coreapidir}/com/holonplatform/core/property/PropertyBoxProperty.html[PropertyBoxProperty^] type can be used, which makes available a builder to create a new `PropertyBox` type property providing the *property set* to use.

For example:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping2,indent=0]
----

The `SUBJECT` property set will be mapped into a _Document_ with the same schema of the previous example, i.e.:

* A `name` String type node at root level.
* A nested `address` document with the `street` and `city` String type nodes.

==== Multi value document nodes

Multi value (array) MongoDB Document nodes can be represented using a `Collection` type property. 

The standard link:{coreapidir}/com/holonplatform/core/property/SetPathProperty.html[SetPathProperty^] and link:{coreapidir}/com/holonplatform/core/property/ListPathProperty.html[ListPathProperty^] types can be used to represent a `Set` or `List` type collection of values.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping3,indent=0]
----
<1> Will be mapped into an array type Document node value and represented as a Java `List`
<2> Will be mapped into an array type Document node value and represented as a Java `Set`

[[DocumentId]]
=== Document id

The MongoDB Datastore supports three data types to represent a *Document id* and to map it to a property:

*1:* The standard `org.bson.types.ObjectId` BSON type:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping4,indent=0]
----

*2:* The `String` type:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping5,indent=0]
----

*1:* The `BigInteger` type:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping6,indent=0]
----

The MongoDB Datastore will perform all the suitable conversions, if required, during the document mapping into and from a `PropertyBox` type.

Regarding the *document id naming strategy*, the following options can be used:

*1:* If a _single_ property is declared as property set identifier and its type is one of the valid document id types (see before), it is used as document id. In this scenario, the property name is irrelevant and *any path name can be used*.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping7,indent=0]
----
<1> The `my_document_id` named property will be used as document id, because it is explicitly declared as property set _identifier_

*2:* Otherwise, if a property with the default `_id` name is available in the propert set and its type is one of the valid document id types (see before), that property is used as document id.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMapping.java[tag=mapping8,indent=0]
----
<1> The `_id` String type property will be used as document id, because it is named with the default `_id` name and its type is a valid document id type

NOTE: When a document id property name different form the standard `_id` is used, the MongoDB Datastore _save_, _insert_ and _update_ operations will always include a `_id` document attribute anyway and its value will be synchonized with the property value declared as document id.

[[DatabaseCollections]]
=== Database collections

For each Datastore operation, the target database *collection name* must be specified using the `DataTarget` representation, providing the collection name as data target name.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=target,indent=0]
----
<1> Declare a `DataTarget` for the `my_collection` database collection name

[[AutoGeneratedIds]]
=== Auto-generated ids

The MongoDB Datastore API supports the retrieving of the auto-generated document id values.

The auto-generated document id values can be obtained from the `OperationResult` object, returned by the Datastore data manipulation operations, through the `getInsertedKeys()` and related methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=ids1,indent=0]
----
<1> Perform a _insert_ operation using the `Datastore` API
<2> Get the document id value using the `ID` property, if available
<4> Get the first auto-generated document id value

The default *BRING_BACK_GENERATED_IDS* `WriteOption` can be provided to the `Datastore` API operation to bring back any auto-generated document id value into the `PropertyBox` instance which was the subject of the operation.

The auto-generated document id value will be setted in the `PropertyBox` instance using the property which acts as property set identifier. See <<DocumentId>>.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastore.java[tag=ids2,indent=0]
----
<1> Document id property declaration using the standard `_id` name
<2> Create the `PropertyBox` value to insert
<3> Perform the _insert_ operation, providing the *BRING_BACK_GENERATED_IDS* write option
<4> The `ID` property value of the inserted `PropertyBox` is updated with the auto-generated document id value

[[SyncMongoDatastore]]
=== Synchronous MongoDB Datastore

The `holon-datastore-mongo-sync` artifact provides the *synchronous* MongoDB `Datastore` API implementation.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-datastore-mongo-sync</artifactId>
<version>{revnumber}</version>
----

The link:{apidir}/com/holonplatform/datastore/mongo/sync/MongoDatastore.html[MongoDatastore^] interface represents the synchronous MongoDB Datastore API implementation, extending the link:{coreapidir}/com/holonplatform/core/datastore/Datastore.html[Datastore^] API.

NOTE: A synchronous link:https://mongodb.github.io/mongo-java-driver[MongoDB Java driver^] is required in classpath in order for the datastore to work.

The `MongoDatastore` API, besides the standard `Datastore` API operations, provides a `builder()` method which can be used to create and configure a `MongoDatastore` API istance.

A `com.mongodb.client.MongoClient` reference is required for the `MongoDatastore` instance setup.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleSyncMongoDatastore.java[tag=builder1,indent=0]
----
<1> Obtain a builder to configure and create a new `MongoDatastore` instance
<2> Set the MongoDB client to use

IMPORTANT: If you want to reach the goal of a *_complete abstraction_* from the persistence store technology and the persistence model, the core `Datastore` API interface should be used instead of the specific `MongoDatastore` API by your application code. This way, the concrete `Datastore` API implementation may be replaced by a different one at any time, without any change to the codebase.

To reach the goal of a complete abstraction from the persistence store technology and the persistence model, the core `Datastore` API interface should be used by your application code, instead of the specific `MongoDatastore` API:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleSyncMongoDatastore.java[tag=builder2,indent=0]
----
<1> Obtain a builder to configure and create a new `MongoDatastore` instance and expose it as a  `Datastore` API type 
<2> Set the MongoDB client to use

For example, given the following property model declaration:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleModel.java[tag=model,indent=0]
----
<1> Document id property using the standard `_id` name and `String` as value type
<2> A `String` type document property declation which maps the `name` document attribute
<3> Property set declaration including the `ID` and `NAME` properties. The `ID` property is explicitly declared as the identifier property, even if in this case it would not have been necessary because the `ID` property is mapped to the standard `_id` document id attribute name.
<4> Data target declation using the `my_collection` database collection name

Below an example of some datastore operations using the _synchronous_ MongoDB Datastore API:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleSyncMongoDatastore.java[tag=ops,indent=0]
----
<1> Build a MongoDB `Datastore` bound to the `test` database name
<2> Save (insert if not present or update otherwise) given `PropertyBox` value in the `my_collection` database collection name (using the `TARGET` declaration)
<3> Get the auto-generated document id value, mapped to the `ID` property declaration
<4> Insert given value using the `BRING_BACK_GENERATED_IDS` default write option
<5> The auto-generated document id value will be setted in the provided `PropertyBox` value, bound to the `ID` property
<6> Update given value
<7> Delete the value
<8> Perform a _count_ query on the `my_collection` database collection, providing some filters
<9> Perform a query on the `my_collection` database collection, providing a filter and a sort declaration and projecting the query results as a stream of `PropertyBox` values
<10> Perform a query to obtain a single value of the `ID` property, if available
<11> Perform a _bulk_ update
<12> Perform a _bulk_ delete

[[AsyncMongoDatastore]]
=== Asynchronous MongoDB Datastore

The `holon-datastore-mongo-async` artifact provides the *asynchronous* MongoDB `AsyncDatastore` API implementation.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-datastore-mongo-async</artifactId>
<version>{revnumber}</version>
----

The link:{apidir}/com/holonplatform/datastore/mongo/async/AsyncMongoDatastore.html[AsyncMongoDatastore^] interface represents the asynchronous MongoDB Datastore API implementation, extending the link:{coreapidir}/com/holonplatform/async/datastore/AsyncDatastore.html[AsyncDatastore^] API.

NOTE: An asynchronous link:https://mongodb.github.io/mongo-java-driver[MongoDB Java driver^] is required in classpath in order for the datastore to work.

The `AsyncMongoDatastore` API, besides the standard `AsyncDatastore` API operations, provides a `builder()` method which can be used to create and configure an `AsyncMongoDatastore` API istance.

A `com.mongodb.reactivestreams.client.MongoClient` reference is required for the `AsyncMongoDatastore` instance setup.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleAsyncMongoDatastore.java[tag=builder1,indent=0]
----
<1> Obtain a builder to configure and create a new `AsyncMongoDatastore` instance
<2> Set the MongoDB client to use

IMPORTANT: If you want to reach the goal of a *_complete abstraction_* from the persistence store technology and the persistence model, the `AsyncDatastore` API interface should be used instead of the specific `AsyncMongoDatastore` API by your application code. This way, the concrete `AsyncDatastore` API implementation may be replaced by a different one at any time, without any change to the codebase.

To reach the goal of a complete abstraction from the persistence store technology and the persistence model, the `AsyncDatastore` API interface should be used by your application code, instead of the specific `AsyncMongoDatastore` API:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleAsyncMongoDatastore.java[tag=builder2,indent=0]
----
<1> Obtain a builder to configure and create a new `AsyncMongoDatastore` instance and expose it as a  `AsyncDatastore` API type 
<2> Set the MongoDB client to use

The `AsyncDatastore` API uses the `java.util.concurrent.CompletionStage` interface to provide the asynchronous operation results.

Below an example of some datastore operations using the _asynchronous_ MongoDB Datastore API:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleAsyncMongoDatastore.java[tag=ops,indent=0]
----
<1> Build a MongoDB `AsyncDatastore` bound to the `test` database name
<2> Save (insert if not present or update otherwise) given `PropertyBox` value in the `my_collection` database collection name (using the `TARGET` declaration)
<3> Get the auto-generated document id value, mapped to the `ID` property declaration
<4> Insert given value using the `BRING_BACK_GENERATED_IDS` default write option
<5> The auto-generated document id value will be setted in the provided `PropertyBox` value, bound to the `ID` property
<6> Update given value
<7> Delete the value
<8> Perform a _count_ query on the `my_collection` database collection, providing some filters
<9> Perform a query on the `my_collection` database collection, providing a filter and a sort declaration and projecting the query results as a stream of `PropertyBox` values
<10> Perform a query to obtain a single value of the `ID` property, if available
<11> Perform a _bulk_ update
<12> Perform a _bulk_ delete

[[ReactiveMongoDatastore]]
=== Reactive MongoDB Datastore

The `holon-datastore-mongo-reactor` artifact provides the *reactive* MongoDB `AsyncDatastore` API implementation, using the link:https://projectreactor.io[Project Reactor^] `Mono` and `Flux` to provide and handle the datastore operations results.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-datastore-mongo-reactor</artifactId>
<version>{revnumber}</version>
----

The link:{apidir}/com/holonplatform/datastore/mongo/reactor/ReactiveMongoDatastore.html[ReactiveMongoDatastore^] interface represents the asynchronous MongoDB Datastore API implementation, extending the link:{reactorapidir}/com/holonplatform/reactor/datastore/ReactiveDatastore.html[ReactiveDatastore^] API.

NOTE: A reactive link:https://mongodb.github.io/mongo-java-driver[MongoDB Java driver^] is required in classpath in order for the datastore to work.

The `ReactiveMongoDatastore` API, besides the standard `ReactiveDatastore` API operations, provides a `builder()` method which can be used to create and configure a `ReactiveMongoDatastore` API istance.

A `com.mongodb.reactivestreams.client.MongoClient` reference is required for the `ReactiveMongoDatastore` instance setup.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleReactiveMongoDatastore.java[tag=builder1,indent=0]
----
<1> Obtain a builder to configure and create a new `ReactiveMongoDatastore` instance
<2> Set the MongoDB client to use

IMPORTANT: If you want to reach the goal of a *_complete abstraction_* from the persistence store technology and the persistence model, the `ReactiveDatastore` API interface should be used instead of the specific `ReactiveMongoDatastore` API by your application code. This way, the concrete `ReactiveDatastore` API implementation may be replaced by a different one at any time, without any change to the codebase.

To reach the goal of a complete abstraction from the persistence store technology and the persistence model, the `ReactiveDatastore` API interface should be used by your application code, instead of the specific `ReactiveMongoDatastore` API:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleReactiveMongoDatastore.java[tag=builder2,indent=0]
----
<1> Obtain a builder to configure and create a new `ReactiveMongoDatastore` instance and expose it as a  `ReactiveDatastore` API type 
<2> Set the MongoDB client to use

The `ReactiveDatastore` API uses the Project Reactor `reactor.core.publisher.Mono` and `reactor.core.publisher.Flux` objects to provide the operation results.

Below an example of some datastore operations using the _reactive_ MongoDB Datastore API:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleReactiveMongoDatastore.java[tag=ops,indent=0]
----
<1> Build a MongoDB `ReactiveDatastore` bound to the `test` database name
<2> Save (insert if not present or update otherwise) given `PropertyBox` value in the `my_collection` database collection name (using the `TARGET` declaration)
<3> Get the auto-generated document id value, mapped to the `ID` property declaration
<4> Insert given value using the `BRING_BACK_GENERATED_IDS` default write option
<5> The auto-generated document id value will be setted in the provided `PropertyBox` value, bound to the `ID` property
<6> Update given value
<7> Delete the value
<8> Perform a _count_ query on the `my_collection` database collection, providing some filters
<9> Perform a query on the `my_collection` database collection, providing a filter and a sort declaration and projecting the query results as a Flux of `PropertyBox` values
<10> Perform a query to obtain a single value of the `ID` property, if available
<11> Perform a _bulk_ update
<12> Perform a _bulk_ delete
