[[MongoDatastoreSpring]]
== Spring ecosystem integration

The `holon-datastore-mongo-spring` artifact provides integration with the https://spring.io[Spring^] framework for the MongoDB Datastore APIs.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-datastore-mongo-spring</artifactId>
<version>{revnumber}</version>
----

[[EnableDatastore]]
=== Enable a MongoDB Datastore bean

A set of Spring configuration class annotations are provided to enable a MongoDB datastore implementation and make it available as a Spring bean.

==== Synchronous MongoDB Datastore

For the *synchronous* `Datastore` implementation, the link:{apidir}/com/holonplatform/datastore/mongo/spring/EnableMongoDatastore.html[EnableMongoDatastore^] annotation can be used on a Spring configuration class.

To enable a MongoDB `Datastore` bean the following preconditions must be met:

* A synchronous MongoDB `com.mongodb.client.MongoClient` type bean must be available. By default, the `mongoClient` bean name is used to detect the MongoClient bean reference. The client reference bean name can be changed using the `mongoClientReference()` annotation attribute.

* A database name must be specified using the `database()` annotation attribute.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring1.java[tag=enablesync,indent=0]
----
<1> Use `test` as database name
<2> MongoClient bean definition
<3> A synchronous `Datastore` bean is configured and available from Spring context

==== Asynchronous MongoDB Datastore

For the *asynchronous* `AsyncDatastore` implementation, the link:{apidir}/com/holonplatform/datastore/mongo/spring/EnableMongoAsyncDatastore.html[EnableMongoAsyncDatastore^] annotation can be used on a Spring configuration class.

To enable a MongoDB `AsyncDatastore` bean the following preconditions must be met:

* An asynchronous MongoDB `com.mongodb.reactivestreams.client.MongoClient` type bean must be available. By default, the `mongoClient` bean name is used to detect the MongoClient bean reference. The client reference bean name can be changed using the `mongoClientReference()` annotation attribute.

* A database name must be specified using the `database()` annotation attribute.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring1.java[tag=enableasync,indent=0]
----
<1> Use `test` as database name
<2> MongoClient bean definition
<3> An asynchronous `AsyncDatastore` bean is configured and available from Spring context

==== Reactive MongoDB Datastore

For the *reactive* `ReactiveDatastore` implementation, the link:{apidir}/com/holonplatform/datastore/mongo/spring/EnableMongoReactiveDatastore.html[EnableMongoReactiveDatastore^] annotation can be used on a Spring configuration class.

To enable a MongoDB `ReactiveDatastore` bean the following preconditions must be met:

* An asynchronous MongoDB `com.mongodb.reactivestreams.client.MongoClient` type bean must be available. By default, the `mongoClient` bean name is used to detect the MongoClient bean reference. The client reference bean name can be changed using the `mongoClientReference()` annotation attribute.

* A database name must be specified using the `database()` annotation attribute.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring1.java[tag=enablereactive,indent=0]
----
<1> Use `test` as database name
<2> MongoClient bean definition
<3> A reactive `ReactiveDatastore` bean is configured and available from Spring context

[[EnableDatastoreConfiguration]]
=== MongoDB Datastore bean configuration

All the annotations described above to enable a MongoDB Datastore bean provide a set of configuration options, which can be setted using the annotations attributes.

==== MongoClient bean name

By default, the `mongoClient` bean name is used to detect the `MongoClient` bean reference to use and bind to the MongoDB Datastore implementation. The client reference bean name can be changed using the `mongoClientReference()` annotation attribute.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring1.java[tag=clientref,indent=0]
----
<1> The `syncMongoClient` bean name is used to enable the synchronous `Datastore` bean
<2> The `asyncMongoClient` bean name is used to enable the asynchronous `AsyncDatastore` bean

==== Enum codec strategy

The enumeration type value codec strategy can be configured using the `enumCodecStrategy()` annotation attribute. See <<EnumCodecStrategy>> for details.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring3.java[tag=enums,indent=0]
----
<1> Set `ORDINAL` as enumeration codec strategy

==== Mongo database configuration

The following annotation attributes can be used to set the default read preference, read concern and write concern to use:

* The `readPreference()` annotation attribute can be use to set the default *read preference*.
* The `readConcern()` annotation attribute can be use to set the default *read concern*.
* The `writeConcern()` annotation attribute can be use to set the default *write concern*.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring3.java[tag=prefs,indent=0]
----
<1> Set the default read preference
<2> Set the default read concern
<3> Set the default write concern

==== Primary mode

Each annotation provides a `primary()` attribute which can be used to control the _primary mode_ of the MongoDB Datastore bean registration.

If the _primary mode_ is set to `PrimaryMode.TRUE`, the `Datastore` bean created with the corresponding annotation will be marked as *primary* in the Spring application context, meaning that will be the one provided by Spring in case of multiple available candidates, when no specific bean name or qualifier is specified in the dependency injection declaration.

TIP: This behaviour is similar to the one obtained with the Spring `@Primary` annotation at bean definition time.

By default, the _primary mode_ is set to `PrimaryMode.AUTO`, meaning that the registred MongoDB Datastore bean will be marked as *primary* only when the `MongoClient` bean to which is bound is registered as primary candidate bean.

[[SpringConfigurationProperties]]
==== MongoDB Datastore configuration properties

When a Mongo Datastore bean is configured using one of the available annotations (`@EnableMongoDatastore`, `@EnableMongoAsyncDatastore`, `@EnableMongoReactiveDatastore`), the Spring environment is automatically used as configuration properties source.

This way, many Datastore configuration settings can be provided using a configuration property with the proper name and value.

The supported configuration properties are:

*1. The standard Datastore configuration properties*, avaible from the link:{coreapidir}/com/holonplatform/core/datastore/DatastoreConfigProperties.html[DatastoreConfigProperties^] property set (See link:holon-core#DatastoreConfiguration[Datastore configuration^]).

The configuration property prefix is `holon.datastore` and the following properties are available:

.Datastore configuration properties
|===
|Name |Type |Meaning

|_holon.datastore._ *trace*
|Boolean (`true` / `false`)
|Enable/disable Datastore operations _tracing_.

|===

*2. An additional set of properties*, provided by the link:{apidir}/com/holonplatform/datastore/mongo/spring/MongoDatastoreConfigProperties.html[MongoDatastoreConfigProperties^] property set, which can be used as an alternative for the annotations attributes described in the previous sections.

.MongoDB Datastore configuration properties
|===
|Name |Type |Meaning

|_holon.datastore.mongo._ *database*
|`String`
|Set the database name to which the Datastore is bound.

|_holon.datastore.mongo._ *primary*
|Boolean (`true` / `false`)
|Mark the MongoDB Datastore bean as _primary_ candidate for dependency injection when more than one definition is available.

|_holon.datastore.mongo._ *read-preference*
|A valid `String` which identifies one of the names listed in the `MongoReadPreference` enumeration.
|Set the default read preference to use.

|_holon.datastore.mongo._ *read-concern*
|A valid `String` which identifies one of the names listed in the `MongoReadConcern` enumeration.
|Set the default read concern to use.

|_holon.datastore.mongo._ *write-concern*
|A valid `String` which identifies one of the names listed in the `MongoWriteConcern` enumeration.
|Set the default write concern to use.

|_holon.datastore.mongo._ *enum-codec-strategy*
|A valid `String` which identifies one of the names listed in the `EnumCodecStrategy` enumeration.
|The enumeration type values codec strategy to use. See <<EnumCodecStrategy>>.
|===

Example of Datastore configuration properties:

[source, text]
----
holon.datastore.trace=true // <1>

holon.datastore.mongo.database=test // <2>
holon.datastore.mongo.read-preference=PRIMARY // <3>
----
<1> Enable tracing
<2> Set the database name to `test`
<3> Set the default read preference to `PRIMARY`

[[SpringDatastoreExtensionConfiguration]]
==== Datastore extension and configuration using the Spring context

The MongoDB Datastore implementation supports the standard link:holon-core.html#SpringDatastoreConfiguration[Holon Platform Datastore Spring integration^] features for Datastore beans configuration and extension, which includes:

* Datastore *configuration post processing* using  link:{coreapidir}/com/holonplatform/spring/DatastorePostProcessor.html[DatastorePostProcessor^] type beans.

* Datastore *extension* through link:{coreapidir}/com/holonplatform/core/ExpressionResolver.html[ExpressionResolver^] registration using link:{coreapidir}/com/holonplatform/spring/DatastoreResolver.html[DatastoreResolver^] annotated beans.

* Datastore *commodity factory* registration using link:{coreapidir}/com/holonplatform/spring/DatastoreCommodityFactory.html[DatastoreCommodityFactory^] annotated beans.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring4.java[tag=config,indent=0]
----
<1> Automatically register a Datastore expression resolver using the `@DatastoreResolver` annotation
<2> Post process Datastore configuration using a `DatastorePostProcessor` type Spring bean
<3> Automatically register a Datastore commodity factory using the `@DatastoreCommodityFactory` annotation

When a Mongo Datastore bean is configured using one of the available annotations (`@EnableMongoDatastore`, `@EnableMongoAsyncDatastore`, `@EnableMongoReactiveDatastore`), the Datastore extension and configuration using the Spring context is automatically enabled.

When one of the available annotation is not used to configure the MongoDB datastore bean, the Datastore extension and configuration support can be explicitly enabled using the `@EnableDatastoreConfiguration` annotation on Spring configuration classes.

=== Multiple MongoDB Datastores configuration

When more than one MongoDB Datastore bean has to be configured using the `@Enable*` annotations, the `dataContextId` attribute can be used to assign a different *data context id* to each MongoDB Datastore bean definition, in order to:

* Provide different sets of configuration properties using the same Spring environment.

* Provide a default _name pattern matching strategy_ with the `MongoClient` bean definition to use for each MongoDB Datastore to configure: if not directly specified with the `mongoClientReference()` attribute, the `MongoClient` bean definition to use for each MongoDB Datastore will be detected in Spring context using the bean name pattern: `mongoClient_{datacontextid}` where `{datacontextid}` is equal to the `dataContextId` attribute of the annotation.

When a _data context id_ is defined, a Spring *qualifier* named the same as the _data context id_ will be associated to the generated MongoDB Datastore bean definitions, and such qualifier can be later used to obtain the right MongoDB Datastore instance through dependency injection.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/mongo/examples/ExampleMongoDatastoreSpring5.java[tag=config,indent=0]
----
<1> Configure the first MongoDB Datastore using `one` as _data context id_: by default the bean named `mongoClient_one` will be used as `MongoClient`
<2> Configure the second MongoDB Datastore using `two` as _data context id_: by default the bean named `mongoClient_two` will be used as `MongoClient`
<3> A specific `Datastore` type bean reference can be obtained using the _data context id_ as *qualifier*

[[MongoDatastoreSpringBoot]]
== Spring Boot integration

The `holon-datastore-mongo-spring-boot` artifact provides integration with https://projects.spring.io/spring-boot[Spring Boot^] for MongoDB Datastores *auto-configuration*.

To enable the Spring Boot MongoDB Datastore auto-configuration features, the following artifact must be included in your project dependencies:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-datastore-mongo-spring-boot</artifactId>
<version>{revnumber}</version>
----

The MongoDB Datastore auto-configuration class support the configuration of the three available MongoDB Datastore implementations:

=== Synchronous MongoDB Datastore

A synchronous MongoDB `Datastore` is auto-configured only when:

* A `MongoDatastore` type bean is not already available from the Spring application context.
* A valid `com.mongodb.client.MongoClient` type bean is available from the Spring application context.

=== Asynchronous MongoDB Datastore

An asynchronous MongoDB `AsyncDatastore` is auto-configured only when:

* A `AsyncMongoDatastore` type bean is not already available from the Spring application context.
* A valid `com.mongodb.reactivestreams.client.MongoClient` type bean is available from the Spring application context.

=== Reactive MongoDB Datastore

A reactive MongoDB `ReactiveDatastore` is auto-configured only when:

* A `ReactiveMongoDatastore` type bean is not already available from the Spring application context.
* A valid `com.mongodb.reactivestreams.client.MongoClient` type bean is available from the Spring application context.
* The `holon-datastore-mongo-reactor` artifact (and the Project Reactor core library) is available from classpath.

=== MongoDB Datastore configuration

The Spring Boot application properties can be used to configure the MongoDB Datastore beans, for example:

.application.yml
[source, yaml]
----
holon: 
  datastore:
    trace: true
  mongo:
    database: test
----

See <<SpringConfigurationProperties>>.

=== Disabling the MongoDB Datastore auto-configuration feature

To disable this auto-configuration feature the link:{apidir}/com/holonplatform/datastore/mongo/spring/boot/MongoDatastoreAutoConfiguration.html[MongoDatastoreAutoConfiguration^] class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={MongoDatastoreAutoConfiguration.class})
----

[[MongoDatastoreSpringBootStarters]]
=== Spring Boot starters

The following _starter_ artifacts are available to provide a quick project configuration setup using Maven dependency system:

*1.* *Default MongoDB Datastore starter* provides the dependencies to the Holon MongoDB Datastore Spring Boot integration artifact `holon-datastore-mongo-spring-boot` and the synchronous and asynchronous MongoDB Datastore implementations.

The *MongoDB Java driver* library is included in the starters dependencies.

Furthermore, the following additional dependencies are provided:

* The link:holon-core.html#SpringBoot[Holon Platform Core Module Spring Boot integration^] base starter (`holon-starter`).
* The base Spring Boot starter (`spring-boot-starter`), see the link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter[Spring Boot starters documentation^] for details.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-starter-mongo-datastore</artifactId>
<version>{revnumber}</version>
----

*2.* *Reactive MongoDB Datastore starter* provides the same dependencies as the default MongoDB Datastore starter, adding the `holon-datastore-mongo-reactor` artifact to provide the reactive MongoDB Datastore implementation and auto-configuration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-starter-mongo-datastore-reactor</artifactId>
<version>{revnumber}</version>
----
