= Holon Platform MongoDB Datastore Module - Reference manual
:description: Holon platform MongoDB Datastore module reference documentation. \
The Holon MongoDB Datastore is the MongoDB reference implementation of the Datastore API.
:revnumber: {project-version}
:apidir: ../api/holon-datastore-mongo
:coreapidir: ../api/holon-core
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2018

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

== TODO

- Query always set as "snapshot"?
- Describe NullFilter and NotNullFilter behaviours

- Document identifier resolution:
-- Property with path/name "_id": valid if type in (ObjectId,String,BigInteger,byte[])
-- _Identifier_ property: valid if only one and type in (ObjectId,String,BigInteger,byte[])

- Document identifier encoding/decoding:
-- When the document identifier property is named differently from "_id", the documents will provide a field with the path name (example "code") AND a "_id" field with the same value treated as ObjectId

