= Holon Platform MongoDB Datastore Module - Reference manual
:description: Holon platform MongoDB Datastore module reference documentation. \
The Holon MongoDB Datastore is the MongoDB reference implementation of the Datastore API, with asynchronous and reactive interactions support.
:revnumber: {project-version}
:apidir: ../api/holon-datastore-mongo
:coreapidir: ../api/holon-core
:reactorapidir: ../api/holon-reactor
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2018

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The *MongoDB Datastore* is the link:https://www.mongodb.com[MongoDB^] reference implementation of the Holon Platform link:{coreapidir}/com/holonplatform/core/datastore/Datastore.html[Datastore^] API. 

TIP: See the link:holon-core.html#Datastore[Datastore^] documentation for further information about the Datastore `API`.

The MongoDB `Datastore` implementation uses the link:https://mongodb.github.io/mongo-java-driver[MongoDB Java Driver^] to perform data access and management operations on MongoDB databases.

=== Sources and contributions

The Holon Platform *MongoDB Datastore* module source code is available from the GitHub repository link:https://github.com/holon-platform/holon-datastore-mongo[https://github.com/holon-platform/holon-datastore-mongo^].

See the repository `README` file for information about:

* The source code structure.
* How to build the module artifacts from sources.
* Where to find the code examples.
* How to contribute to the module development.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.mongo</groupId>
<artifactId>holon-datastore-mongo-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.mongo</groupId>
			<artifactId>holon-datastore-mongo-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

// Inclusions

include::_datastore.adoc[]

include::_spring.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger name for the *MongoDB Datastore* module is `com.holonplatform.datastore.mongo`.

== System requirements

=== Java

The Holon Platform JDBC Datastore module requires https://www.java.com[Java^] *8* or higher.

=== MongoDB Java Drivers

The link:https://mongodb.github.io/mongo-java-driver[MongoDB Java Driver^] version 3.5+ is required to use this module.

The *MongoDB Java Driver version 3.8+* is recommended for a full compatibility with the module APIs, for example to use the transactions management support.

For *asynchronous and reactive* interaction support, the link:http://mongodb.github.io/mongo-java-driver-reactivestreams[MongoDB Reactive Streams Java Driver^] is required.
